### ISSUE TITLE
list index out of range due to downsampling

### ISSUE THREAD

**Issue by cboulay** [Yida-Lin/SigVisualizer#10]
Code [here](https://github.com/Yida-Lin/SigVisualizer/blob/master/paintwidget.py#L58-L64)

```Python
for m in range(round(self.chunkSize/self.downSamplingFactor)):
    if m != round(self.chunkSize/self.downSamplingFactor):
        endIdx = (m+1) * self.downSamplingFactor
        buf = [chunk[n][k] for n in range(m * self.downSamplingFactor, endIdx)]
    else:
        buf = [chunk[n][k] for n in range(m * self.downSamplingFactor, len(chunk))]
```

When `round` rounds up, this goes out of range. e.g., I have a self.chunkSize of 655, self.downSamplingFactor of 16. 655 / 14 = 40.937. On the 41st iteration, m is 40 which != round(<>) so the first path is used with endIdx = 656; too big!

A simple solution would be to make `endIdx = min((m+1) * self.downSamplingFactor, len(chunk))` and then the if-else block isn't needed.

**Comment by Yida-Lin** [comment]
@cboulay Hi Chadwick, thank you for pointing out the bug. I am fixing as instructed.
