### ISSUE TITLE
Rename to all lowercase "sigvisualizer"

### ISSUE THREAD

**Issue by cbrnr** [Yida-Lin/SigVisualizer#5]
Python packages are commonly all lowercase. Would it be possible to rename this repository to "sigvisualizer"? If you are OK with this change, the files `SigVisualizer.png`, `SigVisualizer.py`, `Ui_SigVisualizer.py`, and `Ui_SigVisualizer.ui` should also be renamed accordingly.

**Comment by Yida-Lin** [comment]
Yes, sounds good :) 

Btw, 'sigvisualizer' is a tentative name as I didn't have a better idea yet... Would you suggest anything otherwise? We can of course keep the name to make it a sister project of SigViewer :)

**Comment by cbrnr** [comment]
Great!

Hm, I was thinking that maybe the name should contain LSL. What do you think of "lslviewer"? Or maybe "sigvisualizer" is OK for now (we can always rename later).

**Comment by Yida-Lin** [comment]
Yes, sounds good! Let's keep the nomenclature topic open

**Comment by Yida-Lin** [comment]
Fixed
